version: '3.8'

services:
  gladius:
    build:
      context: .
      dockerfile: ${DOCKERFILE}
    ports:
      - "3000:3000"
      - "9229:9229"
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - gladius-network

networks:
  gladius-network:
    driver: bridge