services:
  gladius:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3000"
      - "9229:9229"
    environment:
      - NODE_ENV=development
      - PORT=3000
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    networks:
      - gladius-network

networks:
  gladius-network:
    driver: bridge